"use client";

import { useState } from "react";
import { ConfirmationDialog } from "@/components/ui/confirmation-dialog";
import { createClient } from "@/lib/supabase/client";
import type { ManagedPartnerContent, ManagedPartnerProperty } from "@/types/database";

type Editor = { kind: "partner"; row: ManagedPartnerContent | null } | { kind: "benefit"; row: ManagedPartnerContent } | { kind: "property"; partner: ManagedPartnerContent; property: ManagedPartnerProperty | null } | null;
type DeleteTarget = { kind: "partner" | "benefit" | "property"; id: string; name: string } | null;
const statusOptions = <><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></>;

export function PartnerManagementWorkspace({ initialRows, initialProperties, initialError }: { initialRows: ManagedPartnerContent[]; initialProperties: ManagedPartnerProperty[]; initialError: string }) {
  const [rows, setRows] = useState(initialRows); const [properties, setProperties] = useState(initialProperties);
  const [message, setMessage] = useState(initialError || `${initialRows.length} partners loaded.`); const [editor, setEditor] = useState<Editor>(null);
  const [pending, setPending] = useState(false); const [deleteTarget, setDeleteTarget] = useState<DeleteTarget>(null);

  async function load(success?: string) {
    const supabase = createClient(); const [content, locations] = await Promise.all([supabase.rpc("list_partner_content_for_management"), supabase.rpc("list_partner_properties_for_management")]);
    if (content.error || locations.error) throw new Error(content.error?.message || locations.error?.message);
    setRows(content.data || []); setProperties(locations.data || []); setMessage(success || `${content.data?.length || 0} partners loaded.`);
  }
  const primary = (partnerId: string) => properties.find((item) => item.partner_id === partnerId && item.is_primary);
  const additional = (partnerId: string) => properties.filter((item) => item.partner_id === partnerId && !item.is_primary);
  function open(next: Editor) { setEditor(next); requestAnimationFrame(() => document.querySelector(".partner-editor-next")?.scrollIntoView({ behavior: "smooth", block: "start" })); }

  async function savePartner(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const row = editor?.kind === "partner" ? editor.row : null; setPending(true); setMessage("Saving partner…");
    try { const supabase = createClient(); const { data: id, error } = await supabase.rpc("save_partner", { p_id: row?.partner_id || null, p_name: String(values.get("name")), p_slug: String(values.get("slug")), p_category: String(values.get("category")), p_description: String(values.get("description")), p_location: String(values.get("location")), p_website: String(values.get("website") || "") || null, p_status: String(values.get("status")) }); if (error) throw new Error(error.message); const partnerId = row?.partner_id || id; const locations = await supabase.rpc("list_partner_properties_for_management"); if (locations.error) throw new Error(locations.error.message); const currentPrimary = locations.data?.find((item) => item.partner_id === partnerId && item.is_primary); if (currentPrimary) { const contact = await supabase.rpc("save_partner_property_contact", { p_property_id: currentPrimary.id, p_email: String(values.get("reservation_email") || "") || null, p_phone: String(values.get("reservation_phone") || "") || null }); if (contact.error) throw new Error(contact.error.message); } setEditor(null); await load(row ? "Partner updated." : "Partner created. Add its member benefit next."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "The partner could not be saved."); } finally { setPending(false); }
  }
  async function saveBenefit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (editor?.kind !== "benefit") return; const form = event.currentTarget; const values = new FormData(form); setPending(true); setMessage("Saving benefit…");
    try { const { error } = await createClient().rpc("save_benefit", { p_id: editor.row.benefit_id, p_partner_id: editor.row.partner_id, p_title: String(values.get("title")), p_description: String(values.get("description")), p_redemption_instructions: String(values.get("redemption_instructions")), p_terms: String(values.get("terms")), p_status: String(values.get("status")) }); if (error) throw new Error(error.message); setEditor(null); await load(editor.row.benefit_id ? "Benefit updated." : "Benefit created."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "The benefit could not be saved."); } finally { setPending(false); }
  }
  async function saveProperty(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (editor?.kind !== "property") return; const values = new FormData(event.currentTarget); setPending(true); setMessage("Saving location…");
    try { const supabase = createClient(); const { data: id, error } = await supabase.rpc("save_partner_property", { p_id: editor.property?.id || null, p_partner_id: editor.partner.partner_id, p_name: String(values.get("name")), p_slug: String(values.get("slug")), p_address: String(values.get("address")), p_status: String(values.get("status")) }); if (error) throw new Error(error.message); const contact = await supabase.rpc("save_partner_property_contact", { p_property_id: editor.property?.id || id, p_email: String(values.get("reservation_email") || "") || null, p_phone: String(values.get("reservation_phone") || "") || null }); if (contact.error) throw new Error(contact.error.message); setEditor(null); await load(editor.property ? "Location updated." : "Location added."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "The location could not be saved."); } finally { setPending(false); }
  }
  async function requestDelete(target: NonNullable<DeleteTarget>) {
    if (target.kind !== "partner") { setDeleteTarget(target); return; } setPending(true); setMessage(`Checking whether ${target.name} can be deleted…`);
    try { const { data, error } = await createClient().rpc("check_partner_deletion", { p_id: target.id }); if (error) throw new Error(error.message); const result = data as { allowed?: boolean; message?: string }; if (!result.allowed) { setMessage(result.message || "This partner cannot be deleted."); return; } setDeleteTarget(target); } catch (error) { setMessage(error instanceof Error ? error.message : "Deletion eligibility could not be checked."); } finally { setPending(false); }
  }
  async function remove() { if (!deleteTarget) return; setPending(true); try { const rpc = deleteTarget.kind === "partner" ? "delete_partner" : deleteTarget.kind === "benefit" ? "delete_benefit" : "delete_partner_property"; const { error } = await createClient().rpc(rpc, { p_id: deleteTarget.id }); if (error) throw new Error(error.message); setDeleteTarget(null); setEditor(null); await load(`${deleteTarget.kind === "property" ? "Location" : deleteTarget.kind[0].toUpperCase() + deleteTarget.kind.slice(1)} deleted.`); } catch (error) { setMessage(error instanceof Error ? error.message : "The record could not be deleted."); } finally { setPending(false); } }

  return <div className="staff-workspace"><div className="staff-toolbar"><p className="form-message" aria-live="polite">{message}</p><div><button className="button button-secondary" type="button" onClick={() => open({ kind: "partner", row: null })}>Add partner</button><button className="button button-secondary" type="button" disabled={pending} onClick={() => load().catch((error) => setMessage(error.message))}>Refresh</button></div></div><div className="partner-admin-list-next">{rows.map((row) => { const locations = additional(row.partner_id); return <article className="partner-admin-card-next" key={row.partner_id}><div className="partner-card-head-next"><div><span className="staff-status">{row.partner_status}</span><h2>{row.partner_name}</h2><p>{row.category} · {row.location}</p></div><div className="partner-card-actions-next"><button className="button button-secondary" type="button" onClick={() => open({ kind: "partner", row })}>Edit partner</button><button className="button button-danger" type="button" onClick={() => requestDelete({ kind: "partner", id: row.partner_id, name: row.partner_name })}>Delete</button></div></div><div className="partner-content-columns-next"><section><p className="eyebrow compact">MEMBER BENEFIT</p>{row.benefit_id ? <><h3>{row.benefit_title}</h3><p>{row.benefit_description}</p><div className="inline-actions-next"><button className="text-action-next" type="button" onClick={() => open({ kind: "benefit", row })}>Edit benefit</button><button className="text-action-next danger-text" type="button" onClick={() => requestDelete({ kind: "benefit", id: row.benefit_id!, name: row.benefit_title! })}>Delete benefit</button></div></> : <><p className="staff-empty">No benefit has been added.</p><button className="button button-secondary" type="button" onClick={() => open({ kind: "benefit", row })}>Add benefit</button></>}</section><section><div className="location-heading-next"><div><p className="eyebrow compact">PROPERTY LOCATIONS</p><h3>{locations.length} locations</h3></div><button className="button button-secondary" type="button" onClick={() => open({ kind: "property", partner: row, property: null })}>Add location</button></div><div className="location-card-grid-next">{locations.map((property) => <button className="location-card-next" type="button" key={property.id} onClick={() => open({ kind: "property", partner: row, property })}><strong>{property.name}</strong><small>{property.status} · {property.reservation_email && property.reservation_phone ? "Contact ready" : "Contact incomplete"}</small></button>)}</div></section></div></article>; })}</div>
  {editor && <aside className="partner-editor-next"><div><p className="eyebrow compact">CONTENT EDITOR</p><h2>{editor.kind === "partner" ? editor.row ? "Edit partner" : "Create partner" : editor.kind === "benefit" ? editor.row.benefit_id ? "Edit member benefit" : "Add member benefit" : editor.property ? "Edit location" : "Add location"}</h2></div><button className="button button-secondary" type="button" onClick={() => setEditor(null)}>Close</button>{editor.kind === "partner" ? <PartnerForm key={editor.row?.partner_id || "new-partner"} row={editor.row} primary={editor.row ? primary(editor.row.partner_id) : undefined} isMulti={Boolean(editor.row && additional(editor.row.partner_id).length)} pending={pending} onSubmit={savePartner} onAddLocation={editor.row ? () => open({ kind: "property", partner: editor.row!, property: null }) : undefined} /> : editor.kind === "benefit" ? <BenefitForm row={editor.row} pending={pending} onSubmit={saveBenefit} /> : <PropertyForm property={editor.property} pending={pending} onSubmit={saveProperty} onDelete={editor.property ? () => requestDelete({ kind: "property", id: editor.property!.id, name: editor.property!.name }) : undefined} />}</aside>}
  <ConfirmationDialog open={Boolean(deleteTarget)} title={`Delete this ${deleteTarget?.kind || "record"} permanently?`} confirmLabel={`Delete ${deleteTarget?.kind || "record"}`} pending={pending} pendingLabel="Deleting…" onClose={() => setDeleteTarget(null)} onConfirm={remove}><p>You are about to permanently delete “{deleteTarget?.name}”.</p><p>This action cannot be undone. Linked records must be removed first.</p></ConfirmationDialog></div>;
}

function PartnerForm({ row, primary, isMulti, pending, onSubmit, onAddLocation }: { row: ManagedPartnerContent | null; primary?: ManagedPartnerProperty; isMulti: boolean; pending: boolean; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onAddLocation?: () => void }) { const [multiLocation, setMultiLocation] = useState(isMulti); return <form className="partner-form-next" onSubmit={onSubmit}><div><label>Partner name<input name="name" defaultValue={row?.partner_name || ""} minLength={2} maxLength={160} required /></label><label>Slug<input name="slug" defaultValue={row?.slug || ""} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label></div><div><label>Category<input name="category" defaultValue={row?.category || ""} required /></label><label>Partner location<input name="location" defaultValue={row?.location || ""} required /></label></div><label>Description<textarea name="description" defaultValue={row?.partner_description || ""} minLength={10} required /></label><div><label>Website<input name="website" type="url" defaultValue={row?.website || ""} /></label><label>Status<select name="status" defaultValue={row?.partner_status || "draft"}>{statusOptions}</select></label></div>{!multiLocation && <><div><label>Reservation email<input name="reservation_email" type="email" defaultValue={primary?.reservation_email || ""} /></label><label>Reservation phone<input name="reservation_phone" type="tel" defaultValue={primary?.reservation_phone || ""} maxLength={30} /></label></div><small>Both reservation contact fields must be present before this single-location partner can be used in the future reservation workflow.</small></>}<label className="multi-location-toggle-next"><input type="checkbox" checked={multiLocation} disabled={isMulti} onChange={(event) => setMultiLocation(event.target.checked)} /><span><strong>This partner has multiple locations</strong><small>{isMulti ? "Additional locations already exist. Remove them before converting this partner back to a single location." : "Enable location management for this partner."}</small></span></label>{multiLocation && !isMulti && <div className="multi-location-action-next"><p>{row ? "Save any partner changes before adding the first location." : "Create the partner first. You can then add its locations."}</p>{row && onAddLocation && <button className="button button-secondary" type="button" onClick={onAddLocation}>Add first location</button>}</div>}<button className="button button-primary" type="submit" disabled={pending}>{pending ? "Saving…" : "Save partner"}</button></form>; }
function BenefitForm({ row, pending, onSubmit }: { row: ManagedPartnerContent; pending: boolean; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { return <form className="partner-form-next" onSubmit={onSubmit}><label>Benefit title<input name="title" defaultValue={row.benefit_title || ""} minLength={3} required /></label><label>Benefit description<textarea name="description" defaultValue={row.benefit_description || ""} minLength={10} required /></label><label>Redemption instructions<textarea name="redemption_instructions" defaultValue={row.redemption_instructions || ""} minLength={5} required /></label><label>Terms<textarea name="terms" defaultValue={row.terms || ""} minLength={3} required /></label><label>Status<select name="status" defaultValue={row.benefit_status || "draft"}>{statusOptions}</select></label><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Saving…" : "Save benefit"}</button></form>; }
function PropertyForm({ property, pending, onSubmit, onDelete }: { property: ManagedPartnerProperty | null; pending: boolean; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onDelete?: () => void }) { return <form className="partner-form-next" onSubmit={onSubmit}><div><label>Location name<input name="name" defaultValue={property?.name || ""} minLength={2} maxLength={160} required /></label><label>Location slug<input name="slug" defaultValue={property?.slug || ""} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label></div><label>Address<textarea name="address" defaultValue={property?.address || ""} minLength={3} required /></label><div><label>Reservation email<input name="reservation_email" type="email" defaultValue={property?.reservation_email || ""} /></label><label>Reservation phone<input name="reservation_phone" type="tel" defaultValue={property?.reservation_phone || ""} maxLength={30} /></label></div><label>Status<select name="status" defaultValue={property?.status || "draft"}>{statusOptions}</select></label><div className="inline-actions-next"><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Saving…" : "Save location"}</button>{onDelete && <button className="button button-danger" type="button" disabled={pending} onClick={onDelete}>Delete location</button>}</div></form>; }
