"use client";
import {useState,type FormEvent} from "react";
import {createClient} from "@/lib/supabase/client";
import {useToast} from "@/components/ui/toast-provider";
import {ConfirmationDialog} from "@/components/ui/confirmation-dialog";
import type {ManagedMembershipTier} from "@/types/database";
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v/100);
export function TierManagementWorkspace({initialTiers,initialError,initialEditId}:{initialTiers:ManagedMembershipTier[];initialError:string;initialEditId?:string}){
 const [tiers,setTiers]=useState(initialTiers);const [editing,setEditing]=useState<ManagedMembershipTier|null>(()=>initialTiers.find(t=>t.id===initialEditId)||null);const [retiring,setRetiring]=useState<ManagedMembershipTier|null>(null);const [pending,setPending]=useState(false);const {notify}=useToast();
 async function reload(message?:string){const {data,error}=await createClient().rpc("list_membership_tiers_for_admin");if(error)throw new Error(error.message);setTiers(data||[]);if(message)notify(message,"success")}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);const f=new FormData(e.currentTarget);try{const {error}=await createClient().rpc("save_membership_tier",{p_id:editing?.id||null,p_name:String(f.get("name")),p_description:String(f.get("description")),p_classification:String(f.get("classification")) as "standard"|"premium",p_price_paise:Math.round(Number(f.get("price"))*100),p_validity_months:f.get("lifetime")==="on"?null:Number(f.get("validity")),p_allocation_limit:String(f.get("limit")||"")?Number(f.get("limit")):null,p_upgrades_enabled:f.get("upgrades")==="on",p_active_term_credit_enabled:f.get("credit")==="on"});if(error)throw new Error(error.message);setEditing(null);e.currentTarget.reset();await reload("Membership tier saved.")}catch(x){notify(x instanceof Error?x.message:"Tier could not be saved.","error")}finally{setPending(false)}}
 async function publish(t:ManagedMembershipTier,slot:number){setPending(true);const {error}=await createClient().rpc("publish_membership_tier",{p_tier_id:t.id,p_display_slot:slot});setPending(false);if(error)return notify(error.message,"error");await reload("Tier published.")}
 async function retire(){if(!retiring)return;setPending(true);const {error}=await createClient().rpc("retire_membership_tier",{p_tier_id:retiring.id});setPending(false);if(error)return notify(error.message,"error");setRetiring(null);await reload("Tier retired.")}
 return <div className="staff-workspace"><p className="form-message">{initialError}</p><div className="tier-admin-layout"><div className="tier-admin-list">{tiers.map(t=><article className="tier-admin-card" key={t.id}><span className="staff-status">{t.status}</span><h2>{t.name}</h2><p>{money(t.price_paise)} · {t.validity_months?`${t.validity_months} months`:"Lifetime"}</p><small>{t.allocation_limit?`${t.allocated}/${t.allocation_limit} allocated`:`${t.allocated} allocated`} · Internal: {t.classification}</small><div><button className="button button-secondary" onClick={()=>setEditing(t)}>Edit</button>{t.status!=="published"&&<><button className="text-button" disabled={pending} onClick={()=>publish(t,1)}>Publish in slot 1</button><button className="text-button" disabled={pending} onClick={()=>publish(t,2)}>Publish in slot 2</button></>}{t.status==="published"&&<button className="button button-danger" disabled={pending} onClick={()=>setRetiring(t)}>Retire</button>}</div></article>)}</div><aside className="event-editor-next"><h2>{editing?"Edit tier":"Create draft tier"}</h2><form className="event-form-next" onSubmit={save}><label>Name<input name="name" defaultValue={editing?.name||""} key={`n-${editing?.id}`} required minLength={3}/></label><label>Description<textarea name="description" defaultValue={editing?.description||""} key={`d-${editing?.id}`} required minLength={10}/></label><label>Internal classification<select name="classification" defaultValue={editing?.classification||"standard"} key={`c-${editing?.id}`}><option value="standard">Non-premium</option><option value="premium">Premium</option></select></label><label>Price (₹)<input name="price" type="number" min={1} defaultValue={editing?editing.price_paise/100:""} required/></label><label><input name="lifetime" type="checkbox" defaultChecked={editing?.validity_months===null}/> Lifetime validity</label><label>Validity in months<input name="validity" type="number" min={1} max={120} defaultValue={editing?.validity_months||12}/></label><label>Allocation limit (blank for unlimited)<input name="limit" type="number" min={1} defaultValue={editing?.allocation_limit||""}/></label><label><input name="upgrades" type="checkbox" defaultChecked={editing?.upgrades_enabled}/> Allow upgrades into this premium tier</label><label><input name="credit" type="checkbox" defaultChecked={editing?.active_term_credit_enabled}/> Credit active membership term</label><button className="button button-primary" disabled={pending}>Save tier</button></form></aside></div><ConfirmationDialog open={Boolean(retiring)} title={`Retire ${retiring?.name || "this tier"}?`} confirmLabel="Retire tier" pending={pending} onClose={()=>setRetiring(null)} onConfirm={retire}><p>The tier will leave its live slot immediately. Existing memberships and payment history will remain unchanged.</p></ConfirmationDialog></div>
}
